### ISSUE TITLE
The 'Draw Mask' box cannot load full image

### ISSUE THREAD

**Issue by zewei-Zhang** [Yujun-Shi/DragDiffusion#17]
Hi, how to load the whole image in the first box or move it to draw the mask?

![theater](https://github.com/Yujun-Shi/DragDiffusion/assets/80893752/3f24f921-2af5-4fbb-ab34-a13ca459e48a)

**Comment by Yujun-Shi** [comment]
Hi, currrently, our code doesn't support arbitrary ratio (only square image is preferred).
For now, you may crop the image into square shape and it can be displayed properly.
I'll add support for arbitrary ratio later.

**Comment by Yujun-Shi** [comment]
Hello, right now, our newest released code supports arbitrary aspect ratios in a correct way.
In our current release, for "Editing Generated Image" function, you can set different (height, width) to first generate an image and then drag the generated image.

Also, when editing a real image, if the height is larger than width, the image can be properly displayed.

However, unfortunately, due to a bug of Gradio, **if the width is larger than height**, the input image still cannot be displayed properly under "Draw Mask" and will be truncated. 

Since this is mainly a Gradio bug, I will close this issue for now.
Thanks again for your feedback, and feel free to re-open this issue if you have any more questions.
