### ISSUE TITLE
Inconsistency between timestep and noise level in DragPipeline.inv_step()

### ISSUE THREAD

**Issue by ZJUSaltFish** [Yujun-Shi/DragDiffusion#31]
Thanks for your excellent work! 

While digging into the code, I found something confusing. This issue is the same as https://github.com/google/prompt-to-prompt/issues/64, about the implementation of DDIM Inversion:

Firstly, according to the formula in ddim paper, the DDIM Inversion writes like this:
![immg](https://github.com/Yujun-Shi/DragDiffusion/assets/114348635/63985194-4fac-4155-8177-302100ad0c1a)

but in DragPipeline.inv_step(), there are:
`
next_step = timestep
timestep = min(timestep - self.scheduler.config.num_train_timesteps // self.scheduler.num_inference_steps, 999)
`,
which renames t as t_next, and t_prev as t.

Therefore, I think the code actually gives:

$$z_{t+1}=\sqrt{\frac{\alpha_t}{\alpha_{t-1}}}z_t+\sqrt{\alpha_t}\cdot\Bigg(\sqrt{\frac{1}{\alpha_t}-1} - \sqrt{\frac{1}{\alpha_{t-1}} - 1}\Bigg)\cdot\epsilon_\theta(z_t,t)$$

This is really confusing to me, please help me out!

**Comment by Yujun-Shi** [comment]
I think this is due to the approximation when numerically solving the ODE when applying DDIM forward and inversion process:
<img width="704" alt="image" src="https://github.com/Yujun-Shi/DragDiffusion/assets/31932863/b724100b-c503-4eb6-8173-69a896757b67">
(image taken from: https://openaccess.thecvf.com/content/CVPR2023/papers/Wallace_EDICT_Exact_Diffusion_Inversion_via_Coupled_Transformations_CVPR_2023_paper.pdf)

**Comment by ZJUSaltFish** [comment]
Thanks for your reply!
I think it does make sense (although a bit counterintuitive)
